<?php include 'includes/header.php' ?>
<div class="about-head">
    <img src="bootstrap/images/back-drop.webp" alt="">
    <div class="hero-content">
        <h1>POWER PURCHASE AGREEMENT</h1>
        <h2><label class="text-light" for="">HOME /</label> SERVICES</h2>

    </div>
</div>
<section class=" work-section text-left section-img pb-1">
    <div class="right">
        <h5><i class="bi bi-sun"></i>Services<i class="bi bi-sun"></i></h5>
        <h2>POWER PURCHASE AGREEMENT</h2>
        <ul class="off-text inline-list">
            <li>
                What is a power purchase agreement? </li>
        </ul>
        <p>A power purchase agreement (PPA) is a popular ‘free solar’ proposition that offers credible companies long
            term financial, accounting and eco benefits. It involves two parties with one business generating the solar
            energy and the other purchasing business purchasing it. A PPA also satisfies companies that prefer to use
            external investors to leverage the benefits of solar energy whilst they reinvest their own funds into core
            business activities.</p>
        <ul class="off-text inline-list">
            <li>
                Free solar and long term cheaper electricity </li>
        </ul>
        <p>Utilising our direct relationships with various energy efficiency asset investment partners, if your business
            satisfies a range of criteria (see below), one of our investors will provide you with a free, fully
            maintained solar PV system – designed and installed by EvoEnergy – in return for a fixed-term lease or
            license of your roof and airspace above your premises.</p>
        <p>A competitive PPA price (per unit of electricity) will also be offered that is cheaper than your existing
            energy provider and linked to an inflation rate that is lower than the energy market, saving you tens of
            thousands of pounds every year for the duration of the PPA and giving your finance team the much-desired
            ability to forecast electricity costs over the long term.</p>
        <ul class="off-text inline-list">
            <li>Solar PPA rates: No upfront costs or ongoing fees
            </li>
        </ul>
        <p>ANo upfront costs or ongoing service fees apply, meaning that you begin to make savings from day one and
            continue to benefit for the full term of the PPA, usually for a minimum of 20 years. At the end of the term,
            it is common practice that the PV system will be gifted to you for a peppercorn fee.</p>
        <ul class="off-text inline-list">
            <li>What is a power purchase agreement?
            </li>
        </ul>
        <p>A power purchase agreement (PPA) is a popular ‘free solar’ proposition that offers credible companies long
            term financial, accounting and eco benefits. It involves two parties with one business generating the solar
            energy and the other purchasing business purchasing it. A PPA also satisfies companies that prefer to use
            external investors to leverage the benefits of solar energy whilst they reinvest their own funds into core
            business activities.</p>

    </div>
</section>
<section class="work-section text-left pt-0">

    <h1>Benefits of a PPA</h1>
    <p>
        A PPA makes perfect business sense and is set up to mutually benefit both you and the investor;
    </p>
    <ul class="off-text">
        <li>Free solar PV system
        </li>
    </ul>
    <p>the system is fully funded by a reputable third party asset investor</p>
    <ul class="off-text">
        <li>Guaranteed savings on energy bills
        </li>
    </ul>
    <p>electricity generated by your PV system is purchased back off the investor at a rate cheaper than your current
        energy provider linked to inflation better than the energy market</p>
    <ul class="off-text">
        <li>No maintenance costs
        </li>
    </ul>
    <p>as part of the agreement, your system will have an ongoing operation and maintenance contract at no cost to
        yourself</p>
    <ul class="off-text">
        <li>Long term budget control
        </li>
    </ul>
    <p>the unit price you pay for electricity generated by the system will be fixed for the term of the agreement,
        allowing you to budget better for the future</p>
    <ul class="off-text">
        <li>Fully transferable
        </li>
    </ul>
    <p>the PPA contract can be transferred to the new occupants should you move to new premises in the future</p>
    <ul class="off-text">
        <li>Zero cost ‘green’ credentials
        </li>
    </ul>
    <p>a zero cost route to improving your company’s CSR, enhancing relations with eco-conscious suppliers & customers
    </p>
</section>
<?php include 'includes/footer.php';?>